const PDFDocument = require("pdfkit");

function statusColor(status) {
  if (status === "blocked") return "#FF5470";
  if (status === "pending_review") return "#FFC94A";
  return "#2DE8A0";
}

function header(doc, title) {
  doc.rect(0, 0, doc.page.width, 70).fill("#0A0714");
  doc.fillColor("#A855F7").fontSize(20).text("CipherShield", 40, 24, { continued: true });
  doc.fillColor("#9C93C4").fontSize(10).text("  ·  AI Fraud Detection & Fair Decision Verification", { baseline: "middle" });
  doc.fillColor("#140E24").fontSize(16).text(title, 40, 90);
  doc.moveTo(40, 115).lineTo(doc.page.width - 40, 115).strokeColor("#2E2354").stroke();
}

function renderReceiptPdf(txn) {
  const doc = new PDFDocument({ margin: 0, size: "A4" });
  header(doc, "Transaction Receipt");

  doc.fontSize(10).fillColor("#333");
  let y = 140;
  const row = (label, value, color) => {
    doc.fillColor("#8A93A3").text(label, 40, y);
    doc.fillColor(color || "#111").text(String(value), 220, y);
    y += 22;
  };

  row("Transaction ID", txn._id);
  row("Sender", txn.userId?.name || String(txn.userId));
  row("Receiver", txn.receiver);
  row("Amount", `${txn.currency} ${txn.amount}`);
  row("Date", new Date(txn.createdAt).toLocaleString());
  row("Status", txn.status.toUpperCase(), statusColor(txn.status));
  row("AI Risk Score", `${txn.riskScore}% (confidence ${(txn.confidence * 100).toFixed(0)}%)`);
  row("Blockchain Hash", txn.blockHash);
  row("ZK Proof Commitment", txn.zkProof?.commitment);
  row("Threshold Met (public)", txn.zkProof?.thresholdMet ? "Yes" : "No");

  y += 10;
  doc.fillColor("#8A93A3").fontSize(9).text("AI explanation:", 40, y);
  y += 16;
  (txn.reasons || []).forEach((r) => {
    doc.fillColor("#333").fontSize(9).text(`• ${r}`, 50, y);
    y += 14;
  });

  doc.fontSize(8).fillColor("#8A93A3").text(
    "This receipt is generated by CipherShield. The blockchain hash and ZK commitment above can be independently re-verified against the platform's audit trail.",
    40,
    doc.page.height - 60,
    { width: doc.page.width - 80 }
  );

  doc.end();
  return doc;
}

function renderCaseReportPdf(fraudCase, txn) {
  const doc = new PDFDocument({ margin: 0, size: "A4" });
  header(doc, `Fraud Case Report — ${fraudCase.caseNumber}`);

  let y = 140;
  const row = (label, value, color) => {
    doc.fillColor("#8A93A3").fontSize(10).text(label, 40, y);
    doc.fillColor(color || "#111").fontSize(10).text(String(value), 220, y, { width: 340 });
    y += 22;
  };

  const txnId = txn?._id || (fraudCase.transactionId && typeof fraudCase.transactionId === "object" ? fraudCase.transactionId._id : fraudCase.transactionId);
  row("Status", fraudCase.status.toUpperCase());
  row("Priority", fraudCase.priority.toUpperCase());
  row("Transaction ID", txnId);
  row("Amount", txn ? `${txn.currency} ${txn.amount}` : "N/A");
  row("AI Risk Score", txn ? `${txn.riskScore}%` : "N/A");
  row("Blockchain Hash", fraudCase.evidence?.blockchainHash || "N/A");
  row("Created", new Date(fraudCase.createdAt).toLocaleString());
  if (fraudCase.resolvedAt) row("Resolved", new Date(fraudCase.resolvedAt).toLocaleString());

  y += 10;
  doc.fillColor("#8A93A3").fontSize(10).text("AI reasons:", 40, y);
  y += 16;
  (txn?.reasons || []).forEach((r) => {
    doc.fillColor("#333").fontSize(9).text(`• ${r}`, 50, y);
    y += 14;
  });

  y += 10;
  doc.fillColor("#8A93A3").fontSize(10).text("Investigation timeline:", 40, y);
  y += 16;
  (fraudCase.timeline || []).forEach((t) => {
    doc.fillColor("#333").fontSize(9).text(`• [${new Date(t.at).toLocaleString()}] ${t.event}`, 50, y, { width: 480 });
    y += 14;
  });

  y += 10;
  doc.fillColor("#8A93A3").fontSize(10).text("Analyst notes:", 40, y);
  y += 16;
  (fraudCase.notes || []).forEach((n) => {
    doc.fillColor("#333").fontSize(9).text(`• ${n.authorName || "Analyst"}: ${n.text}`, 50, y, { width: 480 });
    y += 14;
  });

  if (fraudCase.resolutionSummary) {
    y += 10;
    doc.fillColor("#8A93A3").fontSize(10).text("Resolution summary:", 40, y);
    y += 16;
    doc.fillColor("#333").fontSize(9).text(fraudCase.resolutionSummary, 50, y, { width: 480 });
  }

  doc.end();
  return doc;
}

module.exports = { renderReceiptPdf, renderCaseReportPdf };
